/**
 * Central content + configuration for the BossUp marketing site.
 *
 * Everything that a non-engineer might want to tweak (copy, client list, the
 * Vimeo video, contact details) lives here so it can be changed in one place.
 */

export type NavLink = { label: string; href: string };
export type Client = { name: string; logo?: string };
export type Feature = { title: string; description: string; icon: string };
export type Step = { number: string; title: string; description: string };
export type Stat = {
  value: number;
  prefix?: string;
  suffix?: string;
  decimals?: number;
  label: string;
};
export type Faq = { question: string; answer: string };
export type Testimonial = { quote: string; name: string; role: string };

export const site = {
  name: "BossUp",
  /** A short, swappable tagline used in <title> and the hero. */
  tagline: "Turn frontline talent into frontline leaders.",
  description:
    "BossUp is the mobile-first workforce-development platform that helps hourly and frontline teams build skills, get coached, and grow into leaders — at the scale of the world's busiest airport.",
  url: "https://bossup.app",
  partner: "Workplace Learning Systems",
  audience: "Hartsfield-Jackson Atlanta International Airport",
  audienceShort: "ATL",
  contactEmail: "hello@bossupapp.com",
  /**
   * Placeholder Vimeo video. Swap this single value for the real video id and
   * the sample-film section updates everywhere.
   */
  vimeoVideoId: "76979871",
  /** Path to the downloadable sales brochure (generated by scripts/generate-brochure.mjs). */
  brochurePath: "/bossup-overview.pdf",
} as const;

export const nav: NavLink[] = [
  { label: "Opportunity", href: "#opportunity" },
  { label: "Platform", href: "#platform" },
  { label: "How it works", href: "#how-it-works" },
  { label: "Built for ATL", href: "#atl" },
  { label: "Partnership", href: "#partnership" },
];

/** Clients shown in the scrolling logo banner (rendered as styled wordmarks). */
export const clients: Client[] = [
  { name: "Mazda" },
  { name: "Toyota" },
  { name: "Standard Aero" },
  { name: "Alliance Laundry" },
  { name: "Apple" },
  { name: "DoorDash" },
  { name: "Granite Construction" },
  { name: "San Diego MTA" },
];

export const features: Feature[] = [
  {
    title: "Mobile-first microlearning",
    description:
      "Five-minute lessons built for shift workers — on any phone, in any language, between flights.",
    icon: "Smartphone",
  },
  {
    title: "Real-time coaching",
    description:
      "Nudges and playbooks that turn busy supervisors into mentors, right on the floor.",
    icon: "MessageSquareHeart",
  },
  {
    title: "Role-based skill paths",
    description:
      "Curated tracks that take people from frontline to supervisor to manager.",
    icon: "Route",
  },
  {
    title: "Advancement & mobility",
    description:
      "Clear, visible paths to the next role — and the raise that comes with it.",
    icon: "TrendingUp",
  },
  {
    title: "Manager dashboards",
    description:
      "See skills, progress, and promotion-readiness across every team and terminal.",
    icon: "LayoutDashboard",
  },
  {
    title: "Recognition & culture",
    description:
      "Celebrate wins and build the belonging that keeps great people from leaving.",
    icon: "Award",
  },
];

export const steps: Step[] = [
  {
    number: "01",
    title: "Assess",
    description:
      "Benchmark skills, goals, and gaps for every role — from ramp to retail to operations.",
  },
  {
    number: "02",
    title: "Learn",
    description:
      "Daily microlearning meets people where they are, on the device already in their pocket.",
  },
  {
    number: "03",
    title: "Coach",
    description:
      "Managers get prompts to coach; employees get mentors who help them level up.",
  },
  {
    number: "04",
    title: "Advance",
    description:
      "Track readiness, surface internal candidates, and promote from within with confidence.",
  },
];

/** Illustrative outcomes based on workforce-development benchmarks (not a guarantee). */
export const stats: Stat[] = [
  { value: 34, prefix: "+", suffix: "%", label: "Frontline retention lift" },
  { value: 2.1, suffix: "x", decimals: 1, label: "Faster internal promotions" },
  { value: 28, prefix: "−", suffix: "%", label: "Time-to-productivity" },
  { value: 4.6, suffix: "/5", decimals: 1, label: "Average learner rating" },
];

export const faqs: Faq[] = [
  {
    question: "How fast can we launch a pilot?",
    answer:
      "Most teams are live in under 30 days. We start with one or two departments, prove impact, then scale across terminals.",
  },
  {
    question: "Does it really work for shift and frontline workers?",
    answer:
      "That's exactly who BossUp is built for. Lessons are bite-sized, mobile-first, and designed to fit between shifts — no laptop or login marathon required.",
  },
  {
    question: "Can it support a multilingual workforce?",
    answer:
      "Yes. Content can be delivered in multiple languages so every employee learns and grows in the language they're most comfortable in.",
  },
  {
    question: "How do you measure ROI?",
    answer:
      "We track retention, internal mobility, time-to-productivity, and engagement — and report them against your baseline so finance and operations see the return.",
  },
  {
    question: "How does the Workplace Learning Systems partnership work?",
    answer:
      "BossUp is delivered in partnership with Workplace Learning Systems, combining proven instructional design and implementation services with the BossUp platform.",
  },
];

export const testimonials: Testimonial[] = [
  {
    quote:
      "BossUp gave our ramp and gate teams a reason to stay — and a clear path to grow into leadership.",
    name: "VP of Airport Operations",
    role: "Illustrative",
  },
  {
    quote:
      "We were promoting from within nearly twice as fast within two quarters of launch.",
    name: "Director of People & Culture",
    role: "Illustrative",
  },
  {
    quote:
      "Finally, development that meets frontline workers where they actually are — on their phones, on their schedule.",
    name: "Concessions General Manager",
    role: "Illustrative",
  },
];
